In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
import pandas as pd

pd.options.display.max_rows = 100
pd.options.display.max_columns = 50

In [4]:
import os

for dirname, _, filenames in os.walk('project/data/raw/CSE-CIC-IDS2018'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

project/data/raw/CSE-CIC-IDS2018\02-14-2018.csv
project/data/raw/CSE-CIC-IDS2018\02-15-2018.csv
project/data/raw/CSE-CIC-IDS2018\02-16-2018.csv
project/data/raw/CSE-CIC-IDS2018\02-20-2018.csv
project/data/raw/CSE-CIC-IDS2018\02-21-2018.csv
project/data/raw/CSE-CIC-IDS2018\02-22-2018.csv
project/data/raw/CSE-CIC-IDS2018\02-23-2018.csv
project/data/raw/CSE-CIC-IDS2018\02-28-2018.csv
project/data/raw/CSE-CIC-IDS2018\03-01-2018.csv
project/data/raw/CSE-CIC-IDS2018\03-02-2018.csv

In [ ]:
dataset_list = [
    pd.read_csv("project/data/raw/CSE-CIC-IDS2018/02-14-2018.csv"),
    pd.read_csv("project/data/raw/CSE-CIC-IDS2018/02-15-2018.csv"),
    pd.read_csv("project/data/raw/CSE-CIC-IDS2018/02-16-2018.csv"),
    pd.read_csv("project/data/raw/CSE-CIC-IDS2018/02-20-2018.csv"),
    pd.read_csv("project/data/raw/CSE-CIC-IDS2018/02-21-2018.csv"),
    pd.read_csv("project/data/raw/CSE-CIC-IDS2018/02-22-2018.csv"),
    pd.read_csv("project/data/raw/CSE-CIC-IDS2018/02-23-2018.csv"),
    pd.read_csv("project/data/raw/CSE-CIC-IDS2018/02-28-2018.csv"),
    pd.read_csv("project/data/raw/CSE-CIC-IDS2018/03-01-2018.csv"),
    pd.read_csv("project/data/raw/CSE-CIC-IDS2018/03-02-2018.csv"),
]

dataset = pd.concat(dataset_list, ignore_index=True, axis=0)
del dataset_list

In [23]:
dataset.head()

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,Fwd Pkt Len Std,Bwd Pkt Len Max,Bwd Pkt Len Min,Bwd Pkt Len Mean,Bwd Pkt Len Std,Flow Byts/s,Flow Pkts/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Tot,Fwd IAT Mean,Fwd IAT Std,...,Fwd Blk Rate Avg,Bwd Byts/b Avg,Bwd Pkts/b Avg,Bwd Blk Rate Avg,Subflow Fwd Pkts,Subflow Fwd Byts,Subflow Bwd Pkts,Subflow Bwd Byts,Init Fwd Win Byts,Init Bwd Win Byts,Fwd Act Data Pkts,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label,Flow ID,Src IP,Src Port,Dst IP
0,0,0,14/02/2018 08:31:01,112641719,3,0,0,0,0,0,0.0,0.0,0,0,0.0,0.0,0.0,0.026633,56320859.5,139.300036,56320958,56320761,112641719,56320859.5,139.300036,...,0,0,0,0,3,0,0,0,-1,-1,0,0,0.0,0.0,0,0,56320859.5,139.300036,56320958,56320761,Benign,NaN,NaN,NaN,NaN
1,0,0,14/02/2018 08:33:50,112641466,3,0,0,0,0,0,0.0,0.0,0,0,0.0,0.0,0.0,0.026633,56320733.0,114.551299,56320814,56320652,112641466,56320733.0,114.551299,...,0,0,0,0,3,0,0,0,-1,-1,0,0,0.0,0.0,0,0,56320733.0,114.551299,56320814,56320652,Benign,NaN,NaN,NaN,NaN
2,0,0,14/02/2018 08:36:39,112638623,3,0,0,0,0,0,0.0,0.0,0,0,0.0,0.0,0.0,0.026634,56319311.5,301.934596,56319525,56319098,112638623,56319311.5,301.934596,...,0,0,0,0,3,0,0,0,-1,-1,0,0,0.0,0.0,0,0,56319311.5,301.934596,56319525,56319098,Benign,NaN,NaN,NaN,NaN
3,22,6,14/02/2018 08:40:13,6453966,15,10,1239,2273,744,0,82.6,196.741237,976,0,227.3,371.677892,544.161528,3.873587,268915.25,247443.778966,673900,22,6453966,460997.571429,123109.423588,...,0,0,0,0,15,1239,10,2273,65535,233,6,32,0.0,0.0,0,0,0.0,0.0,0,0,Benign,NaN,NaN,NaN,NaN
4,22,6,14/02/2018 08:40:23,8804066,14,11,1143,2209,744,0,81.642857,203.745545,976,0,200.818182,362.249864,380.733175,2.839597,366836.083333,511356.609733,1928102,21,8804066,677235.846154,532416.970959,...,0,0,0,0,14,1143,11,2209,5808,233,6,32,0.0,0.0,0,0,0.0,0.0,0,0,Benign,NaN,NaN,NaN,NaN

In [24]:
print("Dataset shape: ", dataset.shape)

Dataset shape:  (16233002, 84)

In [ ]:
print("\nDataset info: ")
dataset.info()

Dataset info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16233002 entries, 0 to 16233001
Data columns (total 84 columns):
 #   Column             Dtype
---  ------             -----
 0   Dst Port           object
 1   Protocol           object
 2   Timestamp          object
 3   Flow Duration      object
 4   Tot Fwd Pkts       object
 5   Tot Bwd Pkts       object
 6   TotLen Fwd Pkts    object
 7   TotLen Bwd Pkts    object
 8   Fwd Pkt Len Max    object
 9   Fwd Pkt Len Min    object
 10  Fwd Pkt Len Mean   object
 11  Fwd Pkt Len Std    object
 12  Bwd Pkt Len Max    object
 13  Bwd Pkt Len Min    object
 14  Bwd Pkt Len Mean   object
 15  Bwd Pkt Len Std    object
 16  Flow Byts/s        object
 17  Flow Pkts/s        object
 18  Flow IAT Mean      object
 19  Flow IAT Std       object
 20  Flow IAT Max       object
 21  Flow IAT Min       object
 22  Fwd IAT Tot        object
 23  Fwd IAT Mean       object
 24  Fwd IAT Std        object
 25  Fwd IAT Max        object
 26  Fwd IAT Min        object
 27  Bwd IAT Tot        object
 28  Bwd IAT Mean       object
 29  Bwd IAT Std        object
 30  Bwd IAT Max        object
 31  Bwd IAT Min        object
 32  Fwd PSH Flags      object
 33  Bwd PSH Flags      object
 34  Fwd URG Flags      object
 35  Bwd URG Flags      object
 36  Fwd Header Len     object
 37  Bwd Header Len     object
 38  Fwd Pkts/s         object
 39  Bwd Pkts/s         object
 40  Pkt Len Min        object
 41  Pkt Len Max        object
 42  Pkt Len Mean       object
 43  Pkt Len Std        object
 44  Pkt Len Var        object
 45  FIN Flag Cnt       object
 46  SYN Flag Cnt       object
 47  RST Flag Cnt       object
 48  PSH Flag Cnt       object
 49  ACK Flag Cnt       object
 50  URG Flag Cnt       object
 51  CWE Flag Count     object
 52  ECE Flag Cnt       object
 53  Down/Up Ratio      object
 54  Pkt Size Avg       object
 55  Fwd Seg Size Avg   object
 56  Bwd Seg Size Avg   object
 57  Fwd Byts/b Avg     object
 58  Fwd Pkts/b Avg     object
 59  Fwd Blk Rate Avg   object
 60  Bwd Byts/b Avg     object
 61  Bwd Pkts/b Avg     object
 62  Bwd Blk Rate Avg   object
 63  Subflow Fwd Pkts   object
 64  Subflow Fwd Byts   object
 65  Subflow Bwd Pkts   object
 66  Subflow Bwd Byts   object
 67  Init Fwd Win Byts  object
 68  Init Bwd Win Byts  object
 69  Fwd Act Data Pkts  object
 70  Fwd Seg Size Min   object
 71  Active Mean        object
 72  Active Std         object
 73  Active Max         object
 74  Active Min         object
 75  Idle Mean          object
 76  Idle Std           object
 77  Idle Max           object
 78  Idle Min           object
 79  Label              object
 80  Flow ID            object
 81  Src IP             object
 82  Src Port           float64
 83  Dst IP             object
dtypes: float64(1), object(83)
memory usage: 10.2+ GB

: